name: "Go: Run Tests - Other OS"
on:
  pull_request:
    paths:
      - "go/**"
      - "!go/ql/**" # don't run other-os if only ql/ files changed
      - .github/workflows/go-tests-other-os.yml
      - .github/actions/**
      - codeql-workspace.yml
      - MODULE.bazel
      - .bazelrc
      - misc/bazel/**

permissions:
  contents: read

jobs:
  test-mac:
    name: Test MacOS
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run tests
        uses: ./go/actions/test

  test-win:
    if: github.repository_owner == 'github'
    name: Test Windows
    runs-on: windows-latest-xl
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: dump env bash
        shell: bash
        run: |
          where bazel
          declare -px
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "~1.23.1"
          cache: false
        id: go
      - name: dump env bash again
        shell: bash
        run: |
          where bazel
          declare -px
      - name: test1
        run: |
          C:\npm\prefix\bazel version
      - name: test2
        run: |
          C:\ProgramData\Chocolatey\bin\bazel.exe version
      - name: test3
        run: |
          C:\npm\prefix\bazelisk version
      - name: Run tests
        uses: ./go/actions/test
